export 'movies/movies_providers.dart';
export 'movies/movie_repository_provider.dart';
export 'movies/movie_slideview_provider.dart';
export 'movies/loading_screen_provider.dart';
export 'movies/movie_info_provider.dart';
export 'Functions/theme_provider.dart';
export 'search/search_movies_provider.dart';
export 'actors/actors_by_movie_provider.dart';
export 'actors/actors_repository_provider.dart';
